name: Recode

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL do pliku wideo'
        required: true
      output_filename:
        description: 'Nazwa pliku zip wyjścia'
        required: true
        default: 'out'
      a_bitrate:
        description: 'Bitrate audio 64/96/128/160/192k'
        required: true
        default: '96k'
      vid_quality:
        description: 'Jakość wideo ~15-~30'
        required: true
        default: '27'
      vfr_enabled:
        description: 'Włącz VFR (Variable Frame Rate) (Użyj w pliku wmv)'
        required: true
        default: false
        type: boolean


run-name: >-
  ${{ github.event.inputs.vfr_enabled
    && format('{0} | Audio - {1}, Video - {2}, VFR',
              inputs.output_filename, inputs.a_bitrate, inputs.vid_quality)              
    || format('{0} | Audio - {1}, Video - {2}',
              inputs.output_filename, inputs.a_bitrate, inputs.vid_quality) }}
   
jobs:
  recode:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install ffmpeg
      uses: FedericoCarboni/setup-ffmpeg@v3
      #run: |
     #   brew update
     #   brew install ffmpeg
    
    - name: Run video processing script
      run: |
        python3 ./script.py "${{ github.event.inputs.url }}" "${{ github.event.inputs.a_bitrate }}" "${{ github.event.inputs.vid_quality }}" "${{ github.event.inputs.output_filename }}" "${{ github.event.inputs.vfr_enabled }}"

    - name: Upload processed video
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.inputs.output_filename }}
        path: out/*
