name: Recode

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL for video file'
        required: true
      output_filename:
        description: 'Output file name (for zip)'
        required: true
        default: 'out'
      a_bitrate:
        description: 'Audio bitrate (64k/96k/128k/160k/192k)'
        required: true
        default: '96k'
      vid_quality:
        description: 'Video quality ~15 - ~30 (more = lower quality)'
        required: true
        default: '27'
      vfr_enabled:
        description: 'Enable VFR (for .wmv files)'
        required: true
        default: false
        type: boolean


run-name: >-
  ${{ github.event.inputs.vfr_enabled == 'true'
    && format('{0} | Audio - {1}, Video - {2}, VFR',
              inputs.output_filename, inputs.a_bitrate, inputs.vid_quality)              
    || format('{0} | Audio - {1}, Video - {2}',
              inputs.output_filename, inputs.a_bitrate, inputs.vid_quality) }}
   
jobs:
  recode:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install ffmpeg
      uses: FedericoCarboni/setup-ffmpeg@v3
      #run: |
     #   brew update
     #   brew install ffmpeg
    
    - name: Run video processing script
      shell: bash
      run: |
        python3 ./script.py \
          --url "${{ github.event.inputs.url }}" \
          --qa "${{ github.event.inputs.a_bitrate }}" \
          --qv "${{ github.event.inputs.vid_quality }}" \
          --output "${{ github.event.inputs.output_filename }}" \
          ${{ github.event.inputs.vfr_enabled == 'true' && '--vfr' || '' }}

    - name: Upload processed video
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.inputs.output_filename }}
        path: out/*
